# The URL the site will be built for
base_url = "https://lark.gay"
title = "Lark Space"
description = "Lark's blog and personal site"
compile_sass = false
build_search_index = true
feed_filenames = ["feed.xml"]
author = "Lark"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[[taxonomies]]
name = "tags"
feed = true

[extra]
email = "lark@lark.gay"
license_name = "CC BY-NC 4.0"
license_link = "https://creativecommons.org/licenses/by-nc/4.0/"
copyright_years = "2024"
social_icon = "/assets/icon-padded.webp"
social_icon_type = "image/webp"
social_icon_alt = "A rocket ship taking off"
