base_url = "https://lark.gay"
title = "Lark Space"
description = "Lark's blog and personal site"
compile_sass = false
build_search_index = false
generate_robots_txt = true
generate_sitemap = true
feed_filenames = ["feed.xml"]
author = "Lark"

[markdown]
highlight_code = true
external_links_target_blank = true
bottom_footnotes = true

[[taxonomies]]
name = "tags"
feed = true

[extra]
email = "lark@lark.gay"
license_name = "CC BY-NC 4.0"
license_link = "https://creativecommons.org/licenses/by-nc/4.0/"
copyright_years = "2024"
social_icon = "/assets/icon-padded.webp"
social_icon_type = "image/webp"
social_icon_alt = "A rocket ship taking off"
