# The URL the site will be built for
base_url = "https://lark.gay"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_feeds = true
feed_filenames = ["atom.xml"]

author = "Lark"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
site_title = "Lark Space"
site_description = "Lark's blog and personal site"
email = "lark@lark.gay"
