name = "lark-space-links"
main = "build/index.js"
compatibility_date = "2026-08-05"
account_id = "9d143afa60e911e9904e835bd1db8504"
preview_urls = false

[build]
command = "cargo install -q \"worker-build@^0.8\" && worker-build --release"

[route]
pattern = "links.lark.gay"
custom_domain = true

[[kv_namespaces]]
binding = "KV"
id = "ed2a7afa62bb40d1a877e02d90e7a41a"

[[r2_buckets]]
binding = "R2"
bucket_name = "lark-space-links"
