FROM ghcr.io/processone/ejabberd:latest

USER root

RUN apk add --no-cache curl openssl

USER ejabberd

RUN curl https://get.acme.sh | sh -s -- \
    --install-online \
    --home /home/ejabberd/.acme.sh \
    --nocron

COPY --chown=ejabberd:ejabberd ejabberd.yml /home/ejabberd/conf/ejabberd.yml
COPY --chown=ejabberd:ejabberd entrypoint.sh /home/ejabberd/entrypoint.sh
RUN chmod +x /home/ejabberd/entrypoint.sh

CMD ["/home/ejabberd/entrypoint.sh"]
