app = "lark-space-proxy"
primary_region = "iad"

[build]
dockerfile = "Containerfile"

[[services]]
protocol = "tcp"
internal_port = 8443
auto_start_machines = true
auto_stop_machines = "suspend"
min_machines_running = 0

[[services.ports]]
port = 443
handlers = []

[[services]]
protocol = "tcp"
internal_port = 1965
auto_start_machines = true
auto_stop_machines = "suspend"
min_machines_running = 0

[[services.ports]]
port = 1965
handlers = []

[[vm]]
memory = "512mb"
cpu_kind = "shared"
cpus = 1
