name: "Deploy"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install Dependencies"
        working-directory: ./worker/
        run: npm ci

      - name: "Install Zola"
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.21.0

      - name: "Build"
        run: zola build

      - name: "Deploy"
        uses: cloudflare/wrangler-action@v3
        with:
          environment: prod
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "4"
