name: "Deploy Gemini Capsule"

on:
  push:
    branches:
      - main
    paths:
      - gemini/**
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install cargo-binstall"
        run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

      - name: "Install just"
        run: cargo binstall just

      - name: "Install nu"
        run: cargo binstall nu

      - name: "Install flyctl"
        run: curl -L https://fly.io/install.sh | sh

      - name: "Deploy gemini capsule"
        env:
          FLY_API_TOKEN: {{ secrets.FLY_API_TOKEN }}
        run: just deploy-gemini --yes
